export const GET_PRODUCT="GET_PRODUCT";
export const SET_PRODUCT="SET_PRODUCT";
export const GET_PRODUCT_DETAIL="GET_PRODUCT_DETAIL";
export const SET_PRODUCT_DETAIL="SET_PRODUCT_DETAIL";
export const ADD_PRODUCT_IN_CART="ADD_PRODUCT_IN_CART";
export const SET_PRODUCT_IN_CART="SET_PRODUCT_IN_CART";